name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: priya1shingri
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: priya1shingri/wisecow2:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Update Kubeconfig (**Optional - See note below**):
      # This step is optional if using a mounted Kubeconfig in deploy job
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > ${{ github.workspace }}/kubeconfig
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig

    - name: Deploy your application
      run: |
        export KUBECONFIG=${{ path.home }}/your-kubeconfig-path  # Replace with actual path
        kubectl apply -f deployment.yaml
      env:
        KUBECONFIG: ${{ path.home }}/your-kubeconfig-path  # Replace with actual path

## Updated deployment.yaml (provided by you):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: priya1shingri/wisecow2:latest  # Using image from build job
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: docker-secret
