name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: priya1shingri
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: priya1shingri/wisecow2:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Decode KUBE_CONFIG_DATA and Set KUBECONFIG
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > ${{ github.workspace }}/kubeconfig
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig

    - name: Create TLS Secret
      run: |
        API_SERVER=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')
        kubectl create secret tls tls-secret --cert=tls.crt --key=tls.key --namespace=default --server=$API_SERVER
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig

    - name: Apply Ingress
      run: |
        API_SERVER=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')
        kubectl apply -f ingress.yaml --namespace=default --server=$API_SERVER
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig