name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: priya1shingri
        password: Prt@428198

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: priya1shingri/wisecow2:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Create TLS Secret
      run: |
        kubectl create secret tls tls-secret --cert=tls.crt --key=tls.key
      env:
        KUBECONFIG: ./kubeconfig

    - name: Apply Ingress
      run: |
        kubectl apply -f ingress.yaml
      env:
        KUBECONFIG: ./kubeconfig
