name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: priya1shingri
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: priya1shingri/wisecow2:latest  

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
        kubeconfig: ${{ github.workspace }}/kubeconfig
        service_account_token: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
        context: docker-desktop

    - name: Create TLS Secret
      run: |
        kubectl create secret tls tls-secret --cert=tls.crt --key=tls.key --namespace=default
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig

    - name: Deploy Application
      run: |
        kubectl apply -f deployment.yaml --namespace=default
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig

    - name: Apply Ingress (Optional - Update with your ingress manifest)
      run: |
        kubectl apply -f ingress.yaml --namespace=default
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig
