name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: priya1shingri
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: priya1shingri/wisecow2:latest  

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Create TLS Secret
      run: |
        kubectl create secret tls tls-secret --cert=tls.crt --key=tls.key --namespace=default --server=${{ secrets.KUBE_SERVER }}
      env:
        KUBE_SERVER: ${{ secrets.KUBE_SERVER }}

    - name: Deploy Application
      run: |
        kubectl apply -f deployment.yaml --namespace=default --server=$KUBE_SERVER

    - name: Apply Ingress (Optional - Update with your ingress manifest)
      run: |
        kubectl apply -f ingress.yaml --namespace=default --server=$KUBE_SERVER
