name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (Replace version if needed)
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: priya1shingri
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: priya1shingri/wisecow2:latest
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: priya1shingri/wisecow2:latest  # Replace with your image name and tag

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Decode KUBE_CONFIG_DATA and Set KUBECONFIG
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > ${{ github.workspace }}/kubeconfig
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig


    # Alternatively (if service name not available):
    - name: Create TLS Secret (Using Cluster IP - Adjust IP if needed)
      run: |
        kubectl create secret tls tls-secret --cert=tls.crt --key=tls.key --namespace=default --server=10.105.144.243  # Replace with your cluster IP if different
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig

    - name: my-deployment (Replace with your deployment manifest)
      run: |
        kubectl apply -f deployment.yaml --namespace=default
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig

    - name: Apply Ingress (Optional - Update with your ingress manifest)
      run: |
        API_SERVER=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')
        kubectl apply -f ingress.yaml --namespace=default --server=$API_SERVER
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig
